version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../code:/code
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ../code:/code
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini